fix a run status bug and add a VT-x status check of BIOS
This commit fixs a run status bug and adds a VT-x status check of BIOS.

Change-Id: I124ef8aa7f136f2239cb9e1d3a707e8ffd65c5db

diff --git a/usr/share/gooroom/security/os-protector/gop-daemon b/usr/share/gooroom/security/os-protector/gop-daemon
--- a/usr/share/gooroom/security/os-protector/gop-daemon
+++ b/usr/share/gooroom/security/os-protector/gop-daemon
@@ -17,6 +17,7 @@ GOP_HELPER_PATH="/usr/share/gooroom/security/os-protector/gop-helper"
 PRELOAD_MODULE="/usr/share/gooroom/security/os-protector/preload_module"
 SERVICE_NAME="gop-daemon"
 SERVICE_PATH="/usr/share/gooroom/security/os-protector/$SERVICE_NAME"
+MAIN_DRIVER_NAME="shadow_box"
 MAIN_DRIVER_PATH="/usr/share/gooroom/security/os-protector/shadow_box.ko"
 HELPER_DRIVER_NAME="shadow_box_helper"
 HELPER_DRIVER_PATH="/usr/share/gooroom/security/os-protector/$HELPER_DRIVER_NAME.ko"
@@ -33,7 +34,8 @@ MODULES=""
 ret_value_of_check=
 
 check() {
-	if [ \( -f $MAIN_DRIVER_PATH \) -a \( -f $HELPER_DRIVER_PATH \) -a \( -f $GOP_HELPER_PATH \) ]; then
+	MAIN_DRIVER_LOADED=`lsmod | grep -w $MAIN_DRIVER_NAME || true`
+	if [ \( -f $MAIN_DRIVER_PATH \) -a \( -f $HELPER_DRIVER_PATH \) -a \( -f $GOP_HELPER_PATH \) -a "$MAIN_DRIVER_LOADED" != "" ]; then
 		log_action_msg "$TAG_NAME:" "$SERVICE_NAME active"
 		ret_value_of_check="0"
 	else
@@ -47,15 +49,16 @@ case "$1" in
 	start)
 		log_daemon_msg "$TAG_NAME" "Start Gooroom OS Protector service"
 		log_end_msg 0
-		check
-		logger --id=$$ -p 3 -t $SERVICE_NAME "$TAG_NAME: errorcode=$ret_value_of_check"
-		HELPER_LOADED=`lsmod | grep $HELPER_DRIVER_NAME || true`
 
+		HELPER_LOADED=`lsmod | grep $HELPER_DRIVER_NAME || true`
 		# 시스템 레벨에서 동작하는 중요한 드라이버 및 데몬이므로 중복 로드하지 않도록 처리
 		if [ "$HELPER_LOADED" = "" ]; then
 			$PRELOAD_MODULE
 			$GOP_HELPER_PATH
+			sleep 3
 		fi
+		check
+		logger --id=$$ -p 3 -t $SERVICE_NAME "$TAG_NAME: errorcode=$ret_value_of_check"
 	;;
 
 	stop)
